/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
drop table if exists all_shapes_dist_all_sort_compound_12col;

CREATE TABLE all_shapes_dist_all_sort_compound_12col (
	col_smallint_raw smallint encode raw DEFAULT NULL,
	col_smallint_bytedict smallint encode bytedict DEFAULT NULL,
	col_smallint_delta smallint encode delta DEFAULT NULL,
	col_smallint_lzo smallint encode lzo DEFAULT NULL,
	col_smallint_mostly8 smallint encode mostly8 DEFAULT NULL,
	col_smallint_runlength smallint encode runlength DEFAULT NULL,
	col_smallint_zstd smallint encode zstd DEFAULT NULL,
	col_int_raw int encode raw DEFAULT NULL,
	col_int_bytedict int encode bytedict DEFAULT NULL,
	col_int_delta int encode delta DEFAULT NULL,
	col_int_delta32k int encode delta32k DEFAULT NULL,
	col_int_lzo int encode lzo DEFAULT NULL,
	col_int_mostly8 int encode mostly8 DEFAULT NULL,
	col_int_mostly16 int encode mostly16 DEFAULT NULL,
	col_int_runlength int encode runlength DEFAULT NULL,
	col_int_zstd int encode zstd DEFAULT NULL,
	col_bigint_raw bigint encode raw DEFAULT NULL,
	col_bigint_bytedict bigint encode bytedict DEFAULT NULL,
	col_bigint_delta bigint encode delta DEFAULT NULL,
	col_bigint_delta32k bigint encode delta32k DEFAULT NULL,
	col_bigint_lzo bigint encode lzo DEFAULT NULL,
	col_bigint_mostly8 bigint encode mostly8 DEFAULT NULL,
	col_bigint_mostly16 bigint encode mostly16 DEFAULT NULL,
	col_bigint_mostly32 bigint encode mostly32 DEFAULT NULL,
	col_bigint_runlength bigint encode runlength DEFAULT NULL,
	col_bigint_zstd bigint encode zstd DEFAULT NULL,
	col_decimal_1_0_raw decimal(1, 0) encode raw DEFAULT NULL,
	col_decimal_18_0_raw decimal(18, 0) encode raw DEFAULT NULL,
	col_decimal_18_18_raw decimal(18, 18) encode raw DEFAULT NULL,
	col_decimal_38_0_raw decimal(38, 0) encode raw DEFAULT NULL,
	col_decimal_38_37_raw decimal(38, 37) encode raw DEFAULT NULL,
	col_decimal_1_0_bytedict decimal(1, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_0_bytedict decimal(18, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_18_bytedict decimal(18, 18) encode bytedict DEFAULT NULL,
	col_decimal_38_0_bytedict decimal(38, 0) encode bytedict DEFAULT NULL,
	col_decimal_38_37_bytedict decimal(38, 37) encode bytedict DEFAULT NULL,
	col_decimal_1_0_delta decimal(1, 0) encode delta DEFAULT NULL,
	col_decimal_18_0_delta decimal(18, 0) encode delta DEFAULT NULL,
	col_decimal_18_18_delta decimal(18, 18) encode delta DEFAULT NULL,
	col_decimal_38_0_delta decimal(38, 0) encode delta DEFAULT NULL,
	col_decimal_38_37_delta decimal(38, 37) encode delta DEFAULT NULL,
	col_decimal_1_0_delta32k decimal(1, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_0_delta32k decimal(18, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_18_delta32k decimal(18, 18) encode delta32k DEFAULT NULL,
	col_decimal_38_0_delta32k decimal(38, 0) encode delta32k DEFAULT NULL,
	col_decimal_38_37_delta32k decimal(38, 37) encode delta32k DEFAULT NULL,
	col_decimal_1_0_lzo decimal(1, 0) encode lzo DEFAULT NULL,
	col_decimal_18_0_lzo decimal(18, 0) encode lzo DEFAULT NULL,
	col_decimal_18_18_lzo decimal(18, 18) encode lzo DEFAULT NULL,
	col_decimal_38_0_lzo decimal(38, 0) encode lzo DEFAULT NULL,
	col_decimal_38_37_lzo decimal(38, 37) encode lzo DEFAULT NULL,
	col_decimal_1_0_mostly8 decimal(1, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_0_mostly8 decimal(18, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_18_mostly8 decimal(18, 18) encode mostly8 DEFAULT NULL,
	col_decimal_38_0_mostly8 decimal(38, 0) encode mostly8 DEFAULT NULL,
	col_decimal_38_37_mostly8 decimal(38, 37) encode mostly8 DEFAULT NULL,
	col_decimal_1_0_mostly16 decimal(1, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_0_mostly16 decimal(18, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_18_mostly16 decimal(18, 18) encode mostly16 DEFAULT NULL,
	col_decimal_38_0_mostly16 decimal(38, 0) encode mostly16 DEFAULT NULL,
	col_decimal_38_37_mostly16 decimal(38, 37) encode mostly16 DEFAULT NULL,
	col_decimal_1_0_mostly32 decimal(1, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_0_mostly32 decimal(18, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_18_mostly32 decimal(18, 18) encode mostly32 DEFAULT NULL,
	col_decimal_38_0_mostly32 decimal(38, 0) encode mostly32 DEFAULT NULL,
	col_decimal_38_37_mostly32 decimal(38, 37) encode mostly32 DEFAULT NULL,
	col_decimal_1_0_runlength decimal(1, 0) encode runlength DEFAULT NULL,
	col_decimal_18_0_runlength decimal(18, 0) encode runlength DEFAULT NULL,
	col_decimal_18_18_runlength decimal(18, 18) encode runlength DEFAULT NULL,
	col_decimal_38_0_runlength decimal(38, 0) encode runlength DEFAULT NULL,
	col_decimal_38_37_runlength decimal(38, 37) encode runlength DEFAULT NULL,
	col_decimal_1_0_zstd decimal(1, 0) encode zstd DEFAULT NULL,
	col_decimal_18_0_zstd decimal(18, 0) encode zstd DEFAULT NULL,
	col_decimal_18_18_zstd decimal(18, 18) encode zstd DEFAULT NULL,
	col_decimal_38_0_zstd decimal(38, 0) encode zstd DEFAULT NULL,
	col_decimal_38_37_zstd decimal(38, 37) encode zstd DEFAULT NULL,
	col_float4_raw float4 encode raw DEFAULT NULL,
	col_float4_bytedict float4 encode bytedict DEFAULT NULL,
	col_float4_runlength float4 encode runlength DEFAULT NULL,
	col_float4_zstd float4 encode zstd DEFAULT NULL,
	col_float8_raw float8 encode raw DEFAULT NULL,
	col_float8_bytedict float8 encode bytedict DEFAULT NULL,
	col_float8_runlength float8 encode runlength DEFAULT NULL,
	col_float8_zstd float8 encode zstd DEFAULT NULL,
	col_boolean_raw boolean encode raw DEFAULT NULL,
	col_boolean_runlength boolean encode runlength DEFAULT NULL,
	col_boolean_zstd boolean encode zstd DEFAULT NULL,
	col_char_1_raw char(1) encode raw DEFAULT NULL,
	col_char_255_raw char(255) encode raw DEFAULT NULL,
	col_char_2000_raw char(2000) encode raw DEFAULT NULL,
	col_char_max_raw char(max) encode raw DEFAULT NULL,
	col_char_1_bytedict char(1) encode bytedict DEFAULT NULL,
	col_char_255_bytedict char(255) encode bytedict DEFAULT NULL,
	col_char_2000_bytedict char(2000) encode bytedict DEFAULT NULL,
	col_char_max_bytedict char(max) encode bytedict DEFAULT NULL,
	col_char_1_lzo char(1) encode lzo DEFAULT NULL,
	col_char_255_lzo char(255) encode lzo DEFAULT NULL,
	col_char_2000_lzo char(2000) encode lzo DEFAULT NULL,
	col_char_max_lzo char(max) encode lzo DEFAULT NULL,
	col_char_1_runlength char(1) encode runlength DEFAULT NULL,
	col_char_255_runlength char(255) encode runlength DEFAULT NULL,
	col_char_2000_runlength char(2000) encode runlength DEFAULT NULL,
	col_char_max_runlength char(max) encode runlength DEFAULT NULL,
	col_char_1_zstd char(1) encode zstd DEFAULT NULL,
	col_char_255_zstd char(255) encode zstd DEFAULT NULL,
	col_char_2000_zstd char(2000) encode zstd DEFAULT NULL,
	col_char_max_zstd char(max) encode zstd DEFAULT NULL,
	col_varchar_1_raw varchar(1) encode raw DEFAULT NULL,
	col_varchar_255_raw varchar(255) encode raw DEFAULT NULL,
	col_varchar_2000_raw varchar(2000) encode raw DEFAULT NULL,
	col_varchar_max_raw varchar(max) encode raw DEFAULT NULL,
	col_varchar_1_bytedict varchar(1) encode bytedict DEFAULT NULL,
	col_varchar_255_bytedict varchar(255) encode bytedict DEFAULT NULL,
	col_varchar_2000_bytedict varchar(2000) encode bytedict DEFAULT NULL,
	col_varchar_max_bytedict varchar(max) encode bytedict DEFAULT NULL,
	col_varchar_1_lzo varchar(1) encode lzo DEFAULT NULL,
	col_varchar_255_lzo varchar(255) encode lzo DEFAULT NULL,
	col_varchar_2000_lzo varchar(2000) encode lzo DEFAULT NULL,
	col_varchar_max_lzo varchar(max) encode lzo DEFAULT NULL,
	col_varchar_1_runlength varchar(1) encode runlength DEFAULT NULL,
	col_varchar_255_runlength varchar(255) encode runlength DEFAULT NULL,
	col_varchar_2000_runlength varchar(2000) encode runlength DEFAULT NULL,
	col_varchar_max_runlength varchar(max) encode runlength DEFAULT NULL,
	col_varchar_1_text255 varchar(1) encode text255 DEFAULT NULL,
	col_varchar_255_text255 varchar(255) encode text255 DEFAULT NULL,
	col_varchar_1_text32k varchar(1) encode text32k DEFAULT NULL,
	col_varchar_255_text32k varchar(255) encode text32k DEFAULT NULL,
	col_varchar_2000_text32k varchar(2000) encode text32k DEFAULT NULL,
	col_varchar_max_text32k varchar(max) encode text32k DEFAULT NULL,
	col_varchar_1_zstd varchar(1) encode zstd DEFAULT NULL,
	col_varchar_255_zstd varchar(255) encode zstd DEFAULT NULL,
	col_varchar_2000_zstd varchar(2000) encode zstd DEFAULT NULL,
	col_varchar_max_zstd varchar(max) encode zstd DEFAULT NULL,
	col_date_raw date encode raw DEFAULT NULL,
	col_date_bytedict date encode bytedict DEFAULT NULL,
	col_date_delta date encode delta DEFAULT NULL,
	col_date_delta32k date encode delta32k DEFAULT NULL,
	col_date_lzo date encode lzo DEFAULT NULL,
	col_date_runlength date encode runlength DEFAULT NULL,
	col_date_zstd date encode zstd DEFAULT NULL,
	col_timestamp_raw timestamp encode raw DEFAULT NULL,
	col_timestamp_bytedict timestamp encode bytedict DEFAULT NULL,
	col_timestamp_delta timestamp encode delta DEFAULT NULL,
	col_timestamp_delta32k timestamp encode delta32k DEFAULT NULL,
	col_timestamp_lzo timestamp encode lzo DEFAULT NULL,
	col_timestamp_runlength timestamp encode runlength DEFAULT NULL,
	col_timestamp_zstd timestamp encode zstd DEFAULT NULL,
	col_timestamptz_raw timestamptz encode raw DEFAULT NULL,
	col_timestamptz_bytedict timestamptz encode bytedict DEFAULT NULL,
	col_timestamptz_delta timestamptz encode delta DEFAULT NULL,
	col_timestamptz_delta32k timestamptz encode delta32k DEFAULT NULL,
	col_timestamptz_lzo timestamptz encode lzo DEFAULT NULL,
	col_timestamptz_runlength timestamptz encode runlength DEFAULT NULL,
	col_timestamptz_zstd timestamptz encode zstd DEFAULT NULL
) diststyle all compound sortkey (col_smallint_raw, col_int_raw, col_bigint_raw, col_decimal_1_0_raw, col_float4_raw, col_float8_raw, col_boolean_raw, col_char_1_raw, col_varchar_1_raw, col_date_raw, col_timestamp_raw, col_timestamptz_raw);

copy all_shapes_dist_all_sort_compound_12col from 's3://<S3 Bucket Path>/all_shapes_data_no_nulls_small_' IAM_ROLE '<Associated IAM Role ARN for Redshift Cluster>' region '<S3 Bucket Region>' delimiter ',' REMOVEQUOTES;


drop table if exists all_shapes_dist_even_sort_compound_25col;

CREATE TABLE all_shapes_dist_even_sort_compound_25col (
	col_smallint_raw smallint encode raw DEFAULT NULL,
	col_smallint_bytedict smallint encode bytedict DEFAULT NULL,
	col_smallint_delta smallint encode delta DEFAULT NULL,
	col_smallint_lzo smallint encode lzo DEFAULT NULL,
	col_smallint_mostly8 smallint encode mostly8 DEFAULT NULL,
	col_smallint_runlength smallint encode runlength DEFAULT NULL,
	col_smallint_zstd smallint encode zstd DEFAULT NULL,
	col_int_raw int encode raw DEFAULT NULL,
	col_int_bytedict int encode bytedict DEFAULT NULL,
	col_int_delta int encode delta DEFAULT NULL,
	col_int_delta32k int encode delta32k DEFAULT NULL,
	col_int_lzo int encode lzo DEFAULT NULL,
	col_int_mostly8 int encode mostly8 DEFAULT NULL,
	col_int_mostly16 int encode mostly16 DEFAULT NULL,
	col_int_runlength int encode runlength DEFAULT NULL,
	col_int_zstd int encode zstd DEFAULT NULL,
	col_bigint_raw bigint encode raw DEFAULT NULL,
	col_bigint_bytedict bigint encode bytedict DEFAULT NULL,
	col_bigint_delta bigint encode delta DEFAULT NULL,
	col_bigint_delta32k bigint encode delta32k DEFAULT NULL,
	col_bigint_lzo bigint encode lzo DEFAULT NULL,
	col_bigint_mostly8 bigint encode mostly8 DEFAULT NULL,
	col_bigint_mostly16 bigint encode mostly16 DEFAULT NULL,
	col_bigint_mostly32 bigint encode mostly32 DEFAULT NULL,
	col_bigint_runlength bigint encode runlength DEFAULT NULL,
	col_bigint_zstd bigint encode zstd DEFAULT NULL,
	col_decimal_1_0_raw decimal(1, 0) encode raw DEFAULT NULL,
	col_decimal_18_0_raw decimal(18, 0) encode raw DEFAULT NULL,
	col_decimal_18_18_raw decimal(18, 18) encode raw DEFAULT NULL,
	col_decimal_38_0_raw decimal(38, 0) encode raw DEFAULT NULL,
	col_decimal_38_37_raw decimal(38, 37) encode raw DEFAULT NULL,
	col_decimal_1_0_bytedict decimal(1, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_0_bytedict decimal(18, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_18_bytedict decimal(18, 18) encode bytedict DEFAULT NULL,
	col_decimal_38_0_bytedict decimal(38, 0) encode bytedict DEFAULT NULL,
	col_decimal_38_37_bytedict decimal(38, 37) encode bytedict DEFAULT NULL,
	col_decimal_1_0_delta decimal(1, 0) encode delta DEFAULT NULL,
	col_decimal_18_0_delta decimal(18, 0) encode delta DEFAULT NULL,
	col_decimal_18_18_delta decimal(18, 18) encode delta DEFAULT NULL,
	col_decimal_38_0_delta decimal(38, 0) encode delta DEFAULT NULL,
	col_decimal_38_37_delta decimal(38, 37) encode delta DEFAULT NULL,
	col_decimal_1_0_delta32k decimal(1, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_0_delta32k decimal(18, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_18_delta32k decimal(18, 18) encode delta32k DEFAULT NULL,
	col_decimal_38_0_delta32k decimal(38, 0) encode delta32k DEFAULT NULL,
	col_decimal_38_37_delta32k decimal(38, 37) encode delta32k DEFAULT NULL,
	col_decimal_1_0_lzo decimal(1, 0) encode lzo DEFAULT NULL,
	col_decimal_18_0_lzo decimal(18, 0) encode lzo DEFAULT NULL,
	col_decimal_18_18_lzo decimal(18, 18) encode lzo DEFAULT NULL,
	col_decimal_38_0_lzo decimal(38, 0) encode lzo DEFAULT NULL,
	col_decimal_38_37_lzo decimal(38, 37) encode lzo DEFAULT NULL,
	col_decimal_1_0_mostly8 decimal(1, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_0_mostly8 decimal(18, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_18_mostly8 decimal(18, 18) encode mostly8 DEFAULT NULL,
	col_decimal_38_0_mostly8 decimal(38, 0) encode mostly8 DEFAULT NULL,
	col_decimal_38_37_mostly8 decimal(38, 37) encode mostly8 DEFAULT NULL,
	col_decimal_1_0_mostly16 decimal(1, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_0_mostly16 decimal(18, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_18_mostly16 decimal(18, 18) encode mostly16 DEFAULT NULL,
	col_decimal_38_0_mostly16 decimal(38, 0) encode mostly16 DEFAULT NULL,
	col_decimal_38_37_mostly16 decimal(38, 37) encode mostly16 DEFAULT NULL,
	col_decimal_1_0_mostly32 decimal(1, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_0_mostly32 decimal(18, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_18_mostly32 decimal(18, 18) encode mostly32 DEFAULT NULL,
	col_decimal_38_0_mostly32 decimal(38, 0) encode mostly32 DEFAULT NULL,
	col_decimal_38_37_mostly32 decimal(38, 37) encode mostly32 DEFAULT NULL,
	col_decimal_1_0_runlength decimal(1, 0) encode runlength DEFAULT NULL,
	col_decimal_18_0_runlength decimal(18, 0) encode runlength DEFAULT NULL,
	col_decimal_18_18_runlength decimal(18, 18) encode runlength DEFAULT NULL,
	col_decimal_38_0_runlength decimal(38, 0) encode runlength DEFAULT NULL,
	col_decimal_38_37_runlength decimal(38, 37) encode runlength DEFAULT NULL,
	col_decimal_1_0_zstd decimal(1, 0) encode zstd DEFAULT NULL,
	col_decimal_18_0_zstd decimal(18, 0) encode zstd DEFAULT NULL,
	col_decimal_18_18_zstd decimal(18, 18) encode zstd DEFAULT NULL,
	col_decimal_38_0_zstd decimal(38, 0) encode zstd DEFAULT NULL,
	col_decimal_38_37_zstd decimal(38, 37) encode zstd DEFAULT NULL,
	col_float4_raw float4 encode raw DEFAULT NULL,
	col_float4_bytedict float4 encode bytedict DEFAULT NULL,
	col_float4_runlength float4 encode runlength DEFAULT NULL,
	col_float4_zstd float4 encode zstd DEFAULT NULL,
	col_float8_raw float8 encode raw DEFAULT NULL,
	col_float8_bytedict float8 encode bytedict DEFAULT NULL,
	col_float8_runlength float8 encode runlength DEFAULT NULL,
	col_float8_zstd float8 encode zstd DEFAULT NULL,
	col_boolean_raw boolean encode raw DEFAULT NULL,
	col_boolean_runlength boolean encode runlength DEFAULT NULL,
	col_boolean_zstd boolean encode zstd DEFAULT NULL,
	col_char_1_raw char(1) encode raw DEFAULT NULL,
	col_char_255_raw char(255) encode raw DEFAULT NULL,
	col_char_2000_raw char(2000) encode raw DEFAULT NULL,
	col_char_max_raw char(max) encode raw DEFAULT NULL,
	col_char_1_bytedict char(1) encode bytedict DEFAULT NULL,
	col_char_255_bytedict char(255) encode bytedict DEFAULT NULL,
	col_char_2000_bytedict char(2000) encode bytedict DEFAULT NULL,
	col_char_max_bytedict char(max) encode bytedict DEFAULT NULL,
	col_char_1_lzo char(1) encode lzo DEFAULT NULL,
	col_char_255_lzo char(255) encode lzo DEFAULT NULL,
	col_char_2000_lzo char(2000) encode lzo DEFAULT NULL,
	col_char_max_lzo char(max) encode lzo DEFAULT NULL,
	col_char_1_runlength char(1) encode runlength DEFAULT NULL,
	col_char_255_runlength char(255) encode runlength DEFAULT NULL,
	col_char_2000_runlength char(2000) encode runlength DEFAULT NULL,
	col_char_max_runlength char(max) encode runlength DEFAULT NULL,
	col_char_1_zstd char(1) encode zstd DEFAULT NULL,
	col_char_255_zstd char(255) encode zstd DEFAULT NULL,
	col_char_2000_zstd char(2000) encode zstd DEFAULT NULL,
	col_char_max_zstd char(max) encode zstd DEFAULT NULL,
	col_varchar_1_raw varchar(1) encode raw DEFAULT NULL,
	col_varchar_255_raw varchar(255) encode raw DEFAULT NULL,
	col_varchar_2000_raw varchar(2000) encode raw DEFAULT NULL,
	col_varchar_max_raw varchar(max) encode raw DEFAULT NULL,
	col_varchar_1_bytedict varchar(1) encode bytedict DEFAULT NULL,
	col_varchar_255_bytedict varchar(255) encode bytedict DEFAULT NULL,
	col_varchar_2000_bytedict varchar(2000) encode bytedict DEFAULT NULL,
	col_varchar_max_bytedict varchar(max) encode bytedict DEFAULT NULL,
	col_varchar_1_lzo varchar(1) encode lzo DEFAULT NULL,
	col_varchar_255_lzo varchar(255) encode lzo DEFAULT NULL,
	col_varchar_2000_lzo varchar(2000) encode lzo DEFAULT NULL,
	col_varchar_max_lzo varchar(max) encode lzo DEFAULT NULL,
	col_varchar_1_runlength varchar(1) encode runlength DEFAULT NULL,
	col_varchar_255_runlength varchar(255) encode runlength DEFAULT NULL,
	col_varchar_2000_runlength varchar(2000) encode runlength DEFAULT NULL,
	col_varchar_max_runlength varchar(max) encode runlength DEFAULT NULL,
	col_varchar_1_text255 varchar(1) encode text255 DEFAULT NULL,
	col_varchar_255_text255 varchar(255) encode text255 DEFAULT NULL,
	col_varchar_1_text32k varchar(1) encode text32k DEFAULT NULL,
	col_varchar_255_text32k varchar(255) encode text32k DEFAULT NULL,
	col_varchar_2000_text32k varchar(2000) encode text32k DEFAULT NULL,
	col_varchar_max_text32k varchar(max) encode text32k DEFAULT NULL,
	col_varchar_1_zstd varchar(1) encode zstd DEFAULT NULL,
	col_varchar_255_zstd varchar(255) encode zstd DEFAULT NULL,
	col_varchar_2000_zstd varchar(2000) encode zstd DEFAULT NULL,
	col_varchar_max_zstd varchar(max) encode zstd DEFAULT NULL,
	col_date_raw date encode raw DEFAULT NULL,
	col_date_bytedict date encode bytedict DEFAULT NULL,
	col_date_delta date encode delta DEFAULT NULL,
	col_date_delta32k date encode delta32k DEFAULT NULL,
	col_date_lzo date encode lzo DEFAULT NULL,
	col_date_runlength date encode runlength DEFAULT NULL,
	col_date_zstd date encode zstd DEFAULT NULL,
	col_timestamp_raw timestamp encode raw DEFAULT NULL,
	col_timestamp_bytedict timestamp encode bytedict DEFAULT NULL,
	col_timestamp_delta timestamp encode delta DEFAULT NULL,
	col_timestamp_delta32k timestamp encode delta32k DEFAULT NULL,
	col_timestamp_lzo timestamp encode lzo DEFAULT NULL,
	col_timestamp_runlength timestamp encode runlength DEFAULT NULL,
	col_timestamp_zstd timestamp encode zstd DEFAULT NULL,
	col_timestamptz_raw timestamptz encode raw DEFAULT NULL,
	col_timestamptz_bytedict timestamptz encode bytedict DEFAULT NULL,
	col_timestamptz_delta timestamptz encode delta DEFAULT NULL,
	col_timestamptz_delta32k timestamptz encode delta32k DEFAULT NULL,
	col_timestamptz_lzo timestamptz encode lzo DEFAULT NULL,
	col_timestamptz_runlength timestamptz encode runlength DEFAULT NULL,
	col_timestamptz_zstd timestamptz encode zstd DEFAULT NULL
) diststyle even compound sortkey (col_smallint_raw, col_int_raw, col_bigint_raw, col_decimal_1_0_raw, col_float4_raw, col_float8_raw, col_boolean_raw, col_char_1_raw, col_varchar_1_raw, col_date_raw, col_timestamp_raw, col_timestamptz_raw, col_smallint_bytedict, col_int_bytedict, col_bigint_bytedict, col_decimal_18_0_raw, col_float4_bytedict, col_float8_bytedict, col_boolean_runlength, col_char_255_raw, col_varchar_255_raw, col_date_bytedict, col_timestamp_bytedict, col_timestamptz_bytedict, col_smallint_delta);

copy all_shapes_dist_even_sort_compound_25col from 's3://<S3 Bucket Path>/all_shapes_data_no_nulls_small_' IAM_ROLE '<Associated IAM Role ARN for Redshift Cluster>' region '<S3 Bucket Region>' delimiter ',' REMOVEQUOTES;


drop table if exists all_shapes_dist_key_bigint_sort_interleaved_8col;

CREATE TABLE all_shapes_dist_key_bigint_sort_interleaved_8col (
	col_smallint_raw smallint encode raw DEFAULT NULL,
	col_smallint_bytedict smallint encode bytedict DEFAULT NULL,
	col_smallint_delta smallint encode delta DEFAULT NULL,
	col_smallint_lzo smallint encode lzo DEFAULT NULL,
	col_smallint_mostly8 smallint encode mostly8 DEFAULT NULL,
	col_smallint_runlength smallint encode runlength DEFAULT NULL,
	col_smallint_zstd smallint encode zstd DEFAULT NULL,
	col_int_raw int encode raw DEFAULT NULL,
	col_int_bytedict int encode bytedict DEFAULT NULL,
	col_int_delta int encode delta DEFAULT NULL,
	col_int_delta32k int encode delta32k DEFAULT NULL,
	col_int_lzo int encode lzo DEFAULT NULL,
	col_int_mostly8 int encode mostly8 DEFAULT NULL,
	col_int_mostly16 int encode mostly16 DEFAULT NULL,
	col_int_runlength int encode runlength DEFAULT NULL,
	col_int_zstd int encode zstd DEFAULT NULL,
	col_bigint_raw bigint encode raw DEFAULT NULL,
	col_bigint_bytedict bigint encode bytedict DEFAULT NULL,
	col_bigint_delta bigint encode delta DEFAULT NULL,
	col_bigint_delta32k bigint encode delta32k DEFAULT NULL,
	col_bigint_lzo bigint encode lzo DEFAULT NULL,
	col_bigint_mostly8 bigint encode mostly8 DEFAULT NULL,
	col_bigint_mostly16 bigint encode mostly16 DEFAULT NULL,
	col_bigint_mostly32 bigint encode mostly32 DEFAULT NULL,
	col_bigint_runlength bigint encode runlength DEFAULT NULL,
	col_bigint_zstd bigint encode zstd DEFAULT NULL,
	col_decimal_1_0_raw decimal(1, 0) encode raw DEFAULT NULL,
	col_decimal_18_0_raw decimal(18, 0) encode raw DEFAULT NULL,
	col_decimal_18_18_raw decimal(18, 18) encode raw DEFAULT NULL,
	col_decimal_38_0_raw decimal(38, 0) encode raw DEFAULT NULL,
	col_decimal_38_37_raw decimal(38, 37) encode raw DEFAULT NULL,
	col_decimal_1_0_bytedict decimal(1, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_0_bytedict decimal(18, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_18_bytedict decimal(18, 18) encode bytedict DEFAULT NULL,
	col_decimal_38_0_bytedict decimal(38, 0) encode bytedict DEFAULT NULL,
	col_decimal_38_37_bytedict decimal(38, 37) encode bytedict DEFAULT NULL,
	col_decimal_1_0_delta decimal(1, 0) encode delta DEFAULT NULL,
	col_decimal_18_0_delta decimal(18, 0) encode delta DEFAULT NULL,
	col_decimal_18_18_delta decimal(18, 18) encode delta DEFAULT NULL,
	col_decimal_38_0_delta decimal(38, 0) encode delta DEFAULT NULL,
	col_decimal_38_37_delta decimal(38, 37) encode delta DEFAULT NULL,
	col_decimal_1_0_delta32k decimal(1, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_0_delta32k decimal(18, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_18_delta32k decimal(18, 18) encode delta32k DEFAULT NULL,
	col_decimal_38_0_delta32k decimal(38, 0) encode delta32k DEFAULT NULL,
	col_decimal_38_37_delta32k decimal(38, 37) encode delta32k DEFAULT NULL,
	col_decimal_1_0_lzo decimal(1, 0) encode lzo DEFAULT NULL,
	col_decimal_18_0_lzo decimal(18, 0) encode lzo DEFAULT NULL,
	col_decimal_18_18_lzo decimal(18, 18) encode lzo DEFAULT NULL,
	col_decimal_38_0_lzo decimal(38, 0) encode lzo DEFAULT NULL,
	col_decimal_38_37_lzo decimal(38, 37) encode lzo DEFAULT NULL,
	col_decimal_1_0_mostly8 decimal(1, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_0_mostly8 decimal(18, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_18_mostly8 decimal(18, 18) encode mostly8 DEFAULT NULL,
	col_decimal_38_0_mostly8 decimal(38, 0) encode mostly8 DEFAULT NULL,
	col_decimal_38_37_mostly8 decimal(38, 37) encode mostly8 DEFAULT NULL,
	col_decimal_1_0_mostly16 decimal(1, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_0_mostly16 decimal(18, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_18_mostly16 decimal(18, 18) encode mostly16 DEFAULT NULL,
	col_decimal_38_0_mostly16 decimal(38, 0) encode mostly16 DEFAULT NULL,
	col_decimal_38_37_mostly16 decimal(38, 37) encode mostly16 DEFAULT NULL,
	col_decimal_1_0_mostly32 decimal(1, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_0_mostly32 decimal(18, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_18_mostly32 decimal(18, 18) encode mostly32 DEFAULT NULL,
	col_decimal_38_0_mostly32 decimal(38, 0) encode mostly32 DEFAULT NULL,
	col_decimal_38_37_mostly32 decimal(38, 37) encode mostly32 DEFAULT NULL,
	col_decimal_1_0_runlength decimal(1, 0) encode runlength DEFAULT NULL,
	col_decimal_18_0_runlength decimal(18, 0) encode runlength DEFAULT NULL,
	col_decimal_18_18_runlength decimal(18, 18) encode runlength DEFAULT NULL,
	col_decimal_38_0_runlength decimal(38, 0) encode runlength DEFAULT NULL,
	col_decimal_38_37_runlength decimal(38, 37) encode runlength DEFAULT NULL,
	col_decimal_1_0_zstd decimal(1, 0) encode zstd DEFAULT NULL,
	col_decimal_18_0_zstd decimal(18, 0) encode zstd DEFAULT NULL,
	col_decimal_18_18_zstd decimal(18, 18) encode zstd DEFAULT NULL,
	col_decimal_38_0_zstd decimal(38, 0) encode zstd DEFAULT NULL,
	col_decimal_38_37_zstd decimal(38, 37) encode zstd DEFAULT NULL,
	col_float4_raw float4 encode raw DEFAULT NULL,
	col_float4_bytedict float4 encode bytedict DEFAULT NULL,
	col_float4_runlength float4 encode runlength DEFAULT NULL,
	col_float4_zstd float4 encode zstd DEFAULT NULL,
	col_float8_raw float8 encode raw DEFAULT NULL,
	col_float8_bytedict float8 encode bytedict DEFAULT NULL,
	col_float8_runlength float8 encode runlength DEFAULT NULL,
	col_float8_zstd float8 encode zstd DEFAULT NULL,
	col_boolean_raw boolean encode raw DEFAULT NULL,
	col_boolean_runlength boolean encode runlength DEFAULT NULL,
	col_boolean_zstd boolean encode zstd DEFAULT NULL,
	col_char_1_raw char(1) encode raw DEFAULT NULL,
	col_char_255_raw char(255) encode raw DEFAULT NULL,
	col_char_2000_raw char(2000) encode raw DEFAULT NULL,
	col_char_max_raw char(max) encode raw DEFAULT NULL,
	col_char_1_bytedict char(1) encode bytedict DEFAULT NULL,
	col_char_255_bytedict char(255) encode bytedict DEFAULT NULL,
	col_char_2000_bytedict char(2000) encode bytedict DEFAULT NULL,
	col_char_max_bytedict char(max) encode bytedict DEFAULT NULL,
	col_char_1_lzo char(1) encode lzo DEFAULT NULL,
	col_char_255_lzo char(255) encode lzo DEFAULT NULL,
	col_char_2000_lzo char(2000) encode lzo DEFAULT NULL,
	col_char_max_lzo char(max) encode lzo DEFAULT NULL,
	col_char_1_runlength char(1) encode runlength DEFAULT NULL,
	col_char_255_runlength char(255) encode runlength DEFAULT NULL,
	col_char_2000_runlength char(2000) encode runlength DEFAULT NULL,
	col_char_max_runlength char(max) encode runlength DEFAULT NULL,
	col_char_1_zstd char(1) encode zstd DEFAULT NULL,
	col_char_255_zstd char(255) encode zstd DEFAULT NULL,
	col_char_2000_zstd char(2000) encode zstd DEFAULT NULL,
	col_char_max_zstd char(max) encode zstd DEFAULT NULL,
	col_varchar_1_raw varchar(1) encode raw DEFAULT NULL,
	col_varchar_255_raw varchar(255) encode raw DEFAULT NULL,
	col_varchar_2000_raw varchar(2000) encode raw DEFAULT NULL,
	col_varchar_max_raw varchar(max) encode raw DEFAULT NULL,
	col_varchar_1_bytedict varchar(1) encode bytedict DEFAULT NULL,
	col_varchar_255_bytedict varchar(255) encode bytedict DEFAULT NULL,
	col_varchar_2000_bytedict varchar(2000) encode bytedict DEFAULT NULL,
	col_varchar_max_bytedict varchar(max) encode bytedict DEFAULT NULL,
	col_varchar_1_lzo varchar(1) encode lzo DEFAULT NULL,
	col_varchar_255_lzo varchar(255) encode lzo DEFAULT NULL,
	col_varchar_2000_lzo varchar(2000) encode lzo DEFAULT NULL,
	col_varchar_max_lzo varchar(max) encode lzo DEFAULT NULL,
	col_varchar_1_runlength varchar(1) encode runlength DEFAULT NULL,
	col_varchar_255_runlength varchar(255) encode runlength DEFAULT NULL,
	col_varchar_2000_runlength varchar(2000) encode runlength DEFAULT NULL,
	col_varchar_max_runlength varchar(max) encode runlength DEFAULT NULL,
	col_varchar_1_text255 varchar(1) encode text255 DEFAULT NULL,
	col_varchar_255_text255 varchar(255) encode text255 DEFAULT NULL,
	col_varchar_1_text32k varchar(1) encode text32k DEFAULT NULL,
	col_varchar_255_text32k varchar(255) encode text32k DEFAULT NULL,
	col_varchar_2000_text32k varchar(2000) encode text32k DEFAULT NULL,
	col_varchar_max_text32k varchar(max) encode text32k DEFAULT NULL,
	col_varchar_1_zstd varchar(1) encode zstd DEFAULT NULL,
	col_varchar_255_zstd varchar(255) encode zstd DEFAULT NULL,
	col_varchar_2000_zstd varchar(2000) encode zstd DEFAULT NULL,
	col_varchar_max_zstd varchar(max) encode zstd DEFAULT NULL,
	col_date_raw date encode raw DEFAULT NULL,
	col_date_bytedict date encode bytedict DEFAULT NULL,
	col_date_delta date encode delta DEFAULT NULL,
	col_date_delta32k date encode delta32k DEFAULT NULL,
	col_date_lzo date encode lzo DEFAULT NULL,
	col_date_runlength date encode runlength DEFAULT NULL,
	col_date_zstd date encode zstd DEFAULT NULL,
	col_timestamp_raw timestamp encode raw DEFAULT NULL,
	col_timestamp_bytedict timestamp encode bytedict DEFAULT NULL,
	col_timestamp_delta timestamp encode delta DEFAULT NULL,
	col_timestamp_delta32k timestamp encode delta32k DEFAULT NULL,
	col_timestamp_lzo timestamp encode lzo DEFAULT NULL,
	col_timestamp_runlength timestamp encode runlength DEFAULT NULL,
	col_timestamp_zstd timestamp encode zstd DEFAULT NULL,
	col_timestamptz_raw timestamptz encode raw DEFAULT NULL,
	col_timestamptz_bytedict timestamptz encode bytedict DEFAULT NULL,
	col_timestamptz_delta timestamptz encode delta DEFAULT NULL,
	col_timestamptz_delta32k timestamptz encode delta32k DEFAULT NULL,
	col_timestamptz_lzo timestamptz encode lzo DEFAULT NULL,
	col_timestamptz_runlength timestamptz encode runlength DEFAULT NULL,
	col_timestamptz_zstd timestamptz encode zstd DEFAULT NULL
) distkey (col_bigint_raw) interleaved sortkey (col_smallint_raw, col_int_raw, col_bigint_raw, col_decimal_1_0_raw, col_float4_raw, col_float8_raw, col_boolean_raw, col_char_1_raw);

copy all_shapes_dist_key_bigint_sort_interleaved_8col from 's3://<S3 Bucket Path>/all_shapes_data_no_nulls_small_' IAM_ROLE '<Associated IAM Role ARN for Redshift Cluster>' region '<S3 Bucket Region>' delimiter ',' REMOVEQUOTES;


drop table if exists all_shapes_dist_key_varchar_sort_unsorted;

CREATE TABLE all_shapes_dist_key_varchar_sort_unsorted (
	col_smallint_raw smallint encode raw DEFAULT NULL,
	col_smallint_bytedict smallint encode bytedict DEFAULT NULL,
	col_smallint_delta smallint encode delta DEFAULT NULL,
	col_smallint_lzo smallint encode lzo DEFAULT NULL,
	col_smallint_mostly8 smallint encode mostly8 DEFAULT NULL,
	col_smallint_runlength smallint encode runlength DEFAULT NULL,
	col_smallint_zstd smallint encode zstd DEFAULT NULL,
	col_int_raw int encode raw DEFAULT NULL,
	col_int_bytedict int encode bytedict DEFAULT NULL,
	col_int_delta int encode delta DEFAULT NULL,
	col_int_delta32k int encode delta32k DEFAULT NULL,
	col_int_lzo int encode lzo DEFAULT NULL,
	col_int_mostly8 int encode mostly8 DEFAULT NULL,
	col_int_mostly16 int encode mostly16 DEFAULT NULL,
	col_int_runlength int encode runlength DEFAULT NULL,
	col_int_zstd int encode zstd DEFAULT NULL,
	col_bigint_raw bigint encode raw DEFAULT NULL,
	col_bigint_bytedict bigint encode bytedict DEFAULT NULL,
	col_bigint_delta bigint encode delta DEFAULT NULL,
	col_bigint_delta32k bigint encode delta32k DEFAULT NULL,
	col_bigint_lzo bigint encode lzo DEFAULT NULL,
	col_bigint_mostly8 bigint encode mostly8 DEFAULT NULL,
	col_bigint_mostly16 bigint encode mostly16 DEFAULT NULL,
	col_bigint_mostly32 bigint encode mostly32 DEFAULT NULL,
	col_bigint_runlength bigint encode runlength DEFAULT NULL,
	col_bigint_zstd bigint encode zstd DEFAULT NULL,
	col_decimal_1_0_raw decimal(1, 0) encode raw DEFAULT NULL,
	col_decimal_18_0_raw decimal(18, 0) encode raw DEFAULT NULL,
	col_decimal_18_18_raw decimal(18, 18) encode raw DEFAULT NULL,
	col_decimal_38_0_raw decimal(38, 0) encode raw DEFAULT NULL,
	col_decimal_38_37_raw decimal(38, 37) encode raw DEFAULT NULL,
	col_decimal_1_0_bytedict decimal(1, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_0_bytedict decimal(18, 0) encode bytedict DEFAULT NULL,
	col_decimal_18_18_bytedict decimal(18, 18) encode bytedict DEFAULT NULL,
	col_decimal_38_0_bytedict decimal(38, 0) encode bytedict DEFAULT NULL,
	col_decimal_38_37_bytedict decimal(38, 37) encode bytedict DEFAULT NULL,
	col_decimal_1_0_delta decimal(1, 0) encode delta DEFAULT NULL,
	col_decimal_18_0_delta decimal(18, 0) encode delta DEFAULT NULL,
	col_decimal_18_18_delta decimal(18, 18) encode delta DEFAULT NULL,
	col_decimal_38_0_delta decimal(38, 0) encode delta DEFAULT NULL,
	col_decimal_38_37_delta decimal(38, 37) encode delta DEFAULT NULL,
	col_decimal_1_0_delta32k decimal(1, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_0_delta32k decimal(18, 0) encode delta32k DEFAULT NULL,
	col_decimal_18_18_delta32k decimal(18, 18) encode delta32k DEFAULT NULL,
	col_decimal_38_0_delta32k decimal(38, 0) encode delta32k DEFAULT NULL,
	col_decimal_38_37_delta32k decimal(38, 37) encode delta32k DEFAULT NULL,
	col_decimal_1_0_lzo decimal(1, 0) encode lzo DEFAULT NULL,
	col_decimal_18_0_lzo decimal(18, 0) encode lzo DEFAULT NULL,
	col_decimal_18_18_lzo decimal(18, 18) encode lzo DEFAULT NULL,
	col_decimal_38_0_lzo decimal(38, 0) encode lzo DEFAULT NULL,
	col_decimal_38_37_lzo decimal(38, 37) encode lzo DEFAULT NULL,
	col_decimal_1_0_mostly8 decimal(1, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_0_mostly8 decimal(18, 0) encode mostly8 DEFAULT NULL,
	col_decimal_18_18_mostly8 decimal(18, 18) encode mostly8 DEFAULT NULL,
	col_decimal_38_0_mostly8 decimal(38, 0) encode mostly8 DEFAULT NULL,
	col_decimal_38_37_mostly8 decimal(38, 37) encode mostly8 DEFAULT NULL,
	col_decimal_1_0_mostly16 decimal(1, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_0_mostly16 decimal(18, 0) encode mostly16 DEFAULT NULL,
	col_decimal_18_18_mostly16 decimal(18, 18) encode mostly16 DEFAULT NULL,
	col_decimal_38_0_mostly16 decimal(38, 0) encode mostly16 DEFAULT NULL,
	col_decimal_38_37_mostly16 decimal(38, 37) encode mostly16 DEFAULT NULL,
	col_decimal_1_0_mostly32 decimal(1, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_0_mostly32 decimal(18, 0) encode mostly32 DEFAULT NULL,
	col_decimal_18_18_mostly32 decimal(18, 18) encode mostly32 DEFAULT NULL,
	col_decimal_38_0_mostly32 decimal(38, 0) encode mostly32 DEFAULT NULL,
	col_decimal_38_37_mostly32 decimal(38, 37) encode mostly32 DEFAULT NULL,
	col_decimal_1_0_runlength decimal(1, 0) encode runlength DEFAULT NULL,
	col_decimal_18_0_runlength decimal(18, 0) encode runlength DEFAULT NULL,
	col_decimal_18_18_runlength decimal(18, 18) encode runlength DEFAULT NULL,
	col_decimal_38_0_runlength decimal(38, 0) encode runlength DEFAULT NULL,
	col_decimal_38_37_runlength decimal(38, 37) encode runlength DEFAULT NULL,
	col_decimal_1_0_zstd decimal(1, 0) encode zstd DEFAULT NULL,
	col_decimal_18_0_zstd decimal(18, 0) encode zstd DEFAULT NULL,
	col_decimal_18_18_zstd decimal(18, 18) encode zstd DEFAULT NULL,
	col_decimal_38_0_zstd decimal(38, 0) encode zstd DEFAULT NULL,
	col_decimal_38_37_zstd decimal(38, 37) encode zstd DEFAULT NULL,
	col_float4_raw float4 encode raw DEFAULT NULL,
	col_float4_bytedict float4 encode bytedict DEFAULT NULL,
	col_float4_runlength float4 encode runlength DEFAULT NULL,
	col_float4_zstd float4 encode zstd DEFAULT NULL,
	col_float8_raw float8 encode raw DEFAULT NULL,
	col_float8_bytedict float8 encode bytedict DEFAULT NULL,
	col_float8_runlength float8 encode runlength DEFAULT NULL,
	col_float8_zstd float8 encode zstd DEFAULT NULL,
	col_boolean_raw boolean encode raw DEFAULT NULL,
	col_boolean_runlength boolean encode runlength DEFAULT NULL,
	col_boolean_zstd boolean encode zstd DEFAULT NULL,
	col_char_1_raw char(1) encode raw DEFAULT NULL,
	col_char_255_raw char(255) encode raw DEFAULT NULL,
	col_char_2000_raw char(2000) encode raw DEFAULT NULL,
	col_char_max_raw char(max) encode raw DEFAULT NULL,
	col_char_1_bytedict char(1) encode bytedict DEFAULT NULL,
	col_char_255_bytedict char(255) encode bytedict DEFAULT NULL,
	col_char_2000_bytedict char(2000) encode bytedict DEFAULT NULL,
	col_char_max_bytedict char(max) encode bytedict DEFAULT NULL,
	col_char_1_lzo char(1) encode lzo DEFAULT NULL,
	col_char_255_lzo char(255) encode lzo DEFAULT NULL,
	col_char_2000_lzo char(2000) encode lzo DEFAULT NULL,
	col_char_max_lzo char(max) encode lzo DEFAULT NULL,
	col_char_1_runlength char(1) encode runlength DEFAULT NULL,
	col_char_255_runlength char(255) encode runlength DEFAULT NULL,
	col_char_2000_runlength char(2000) encode runlength DEFAULT NULL,
	col_char_max_runlength char(max) encode runlength DEFAULT NULL,
	col_char_1_zstd char(1) encode zstd DEFAULT NULL,
	col_char_255_zstd char(255) encode zstd DEFAULT NULL,
	col_char_2000_zstd char(2000) encode zstd DEFAULT NULL,
	col_char_max_zstd char(max) encode zstd DEFAULT NULL,
	col_varchar_1_raw varchar(1) encode raw DEFAULT NULL,
	col_varchar_255_raw varchar(255) encode raw DEFAULT NULL,
	col_varchar_2000_raw varchar(2000) encode raw DEFAULT NULL,
	col_varchar_max_raw varchar(max) encode raw DEFAULT NULL,
	col_varchar_1_bytedict varchar(1) encode bytedict DEFAULT NULL,
	col_varchar_255_bytedict varchar(255) encode bytedict DEFAULT NULL,
	col_varchar_2000_bytedict varchar(2000) encode bytedict DEFAULT NULL,
	col_varchar_max_bytedict varchar(max) encode bytedict DEFAULT NULL,
	col_varchar_1_lzo varchar(1) encode lzo DEFAULT NULL,
	col_varchar_255_lzo varchar(255) encode lzo DEFAULT NULL,
	col_varchar_2000_lzo varchar(2000) encode lzo DEFAULT NULL,
	col_varchar_max_lzo varchar(max) encode lzo DEFAULT NULL,
	col_varchar_1_runlength varchar(1) encode runlength DEFAULT NULL,
	col_varchar_255_runlength varchar(255) encode runlength DEFAULT NULL,
	col_varchar_2000_runlength varchar(2000) encode runlength DEFAULT NULL,
	col_varchar_max_runlength varchar(max) encode runlength DEFAULT NULL,
	col_varchar_1_text255 varchar(1) encode text255 DEFAULT NULL,
	col_varchar_255_text255 varchar(255) encode text255 DEFAULT NULL,
	col_varchar_1_text32k varchar(1) encode text32k DEFAULT NULL,
	col_varchar_255_text32k varchar(255) encode text32k DEFAULT NULL,
	col_varchar_2000_text32k varchar(2000) encode text32k DEFAULT NULL,
	col_varchar_max_text32k varchar(max) encode text32k DEFAULT NULL,
	col_varchar_1_zstd varchar(1) encode zstd DEFAULT NULL,
	col_varchar_255_zstd varchar(255) encode zstd DEFAULT NULL,
	col_varchar_2000_zstd varchar(2000) encode zstd DEFAULT NULL,
	col_varchar_max_zstd varchar(max) encode zstd DEFAULT NULL,
	col_date_raw date encode raw DEFAULT NULL,
	col_date_bytedict date encode bytedict DEFAULT NULL,
	col_date_delta date encode delta DEFAULT NULL,
	col_date_delta32k date encode delta32k DEFAULT NULL,
	col_date_lzo date encode lzo DEFAULT NULL,
	col_date_runlength date encode runlength DEFAULT NULL,
	col_date_zstd date encode zstd DEFAULT NULL,
	col_timestamp_raw timestamp encode raw DEFAULT NULL,
	col_timestamp_bytedict timestamp encode bytedict DEFAULT NULL,
	col_timestamp_delta timestamp encode delta DEFAULT NULL,
	col_timestamp_delta32k timestamp encode delta32k DEFAULT NULL,
	col_timestamp_lzo timestamp encode lzo DEFAULT NULL,
	col_timestamp_runlength timestamp encode runlength DEFAULT NULL,
	col_timestamp_zstd timestamp encode zstd DEFAULT NULL,
	col_timestamptz_raw timestamptz encode raw DEFAULT NULL,
	col_timestamptz_bytedict timestamptz encode bytedict DEFAULT NULL,
	col_timestamptz_delta timestamptz encode delta DEFAULT NULL,
	col_timestamptz_delta32k timestamptz encode delta32k DEFAULT NULL,
	col_timestamptz_lzo timestamptz encode lzo DEFAULT NULL,
	col_timestamptz_runlength timestamptz encode runlength DEFAULT NULL,
	col_timestamptz_zstd timestamptz encode zstd DEFAULT NULL
) distkey (col_varchar_1_raw) ;

copy all_shapes_dist_key_varchar_sort_unsorted from 's3://<S3 Bucket Path>/all_shapes_data_no_nulls_small_' IAM_ROLE '<Associated IAM Role ARN for Redshift Cluster>' region '<S3 Bucket Region>' delimiter ',' REMOVEQUOTES;

drop table if exists all_shapes_dist_key_varchar_sort_unsorted_default_encoding;

CREATE TABLE all_shapes_dist_key_varchar_sort_unsorted_default_encoding (
	col_smallint smallint DEFAULT NULL,
	col_int int DEFAULT NULL,
	col_bigint bigint DEFAULT NULL,
	col_decimal_1_0 decimal(1, 0) DEFAULT NULL,
	col_decimal_18_0 decimal(18, 0) DEFAULT NULL,
	col_decimal_18_18 decimal(18, 18) DEFAULT NULL,
	col_decimal_38_0 decimal(38, 0) DEFAULT NULL,
	col_decimal_38_37 decimal(38, 37) DEFAULT NULL,
	col_float4 float4 DEFAULT NULL,
	col_float8 float8 DEFAULT NULL,
	col_boolean boolean DEFAULT NULL,
	col_char_1 char(1) DEFAULT NULL,
	col_char_255 char(255) DEFAULT NULL,
	col_char_2000 char(2000) DEFAULT NULL,
	col_char_max char(max) DEFAULT NULL,
	col_varchar_1 varchar(1) DEFAULT NULL,
	col_varchar_255 varchar(255) DEFAULT NULL,
	col_varchar_2000 varchar(2000) DEFAULT NULL,
	col_varchar_max varchar(max) DEFAULT NULL,
	col_date date DEFAULT NULL,
	col_timestamp timestamp DEFAULT NULL,
	col_timestamptz timestamptz DEFAULT NULL
) distkey (col_varchar_1) ;

insert into all_shapes_dist_key_varchar_sort_unsorted_default_encoding(
    col_smallint,
	col_int,
	col_bigint,
	col_decimal_1_0,
	col_decimal_18_0,
	col_decimal_18_18,
	col_decimal_38_0,
	col_decimal_38_37,
	col_float4,
	col_float8,
	col_boolean,
	col_char_1,
	col_char_255,
	col_char_2000,
	col_char_max,
	col_varchar_1,
	col_varchar_255,
	col_varchar_2000,
	col_varchar_max,
	col_date,
	col_timestamp,
	col_timestamptz
) select
	col_smallint_raw,
	col_int_raw,
	col_bigint_raw,
	col_decimal_1_0_raw,
	col_decimal_18_0_raw,
	col_decimal_18_18_raw,
	col_decimal_38_0_raw,
	col_decimal_38_37_raw,
	col_float4_raw,
	col_float8_raw,
	col_boolean_raw,
	col_char_1_raw,
	col_char_255_raw,
	col_char_2000_raw,
	col_char_max_raw,
	col_varchar_1_raw,
	col_varchar_255_raw,
	col_varchar_2000_raw,
	col_varchar_max_raw,
	col_date_raw,
	col_timestamp_raw,
	col_timestamptz_zstd
from all_shapes_dist_key_varchar_sort_unsorted;

